# PARAMETROS DE CONFIGURACION GLOBAL DE LA APLICACION
---
config:
  debug_mode: false

  # PARA MOSTRAR O NO EL BOTON DE LA AUDITORIA DE LOS FORMULARIOS
  audit_mode: true

  # CONTROL DE ACCESO POR IP
  ip_control: true

  # FORMATOS DE EXPORTACION DE INFORMACION
  export_types:
    - xls
    - xml
    - cvs
    - Yaml

  # ENTORNO DE LA APLICACION
  app:
    name: Cpanel
    url: http://www.regantesvirgensalud.com/Cpanel
    path: /Cpanel
    framework: bin/albatronic/
    urlParent: http://www.regantesvirgensalud.com/Pcae

  # INFORMACION PARA SEO
  meta:
    author: 'Informática Albatronic, SL'
    revisitAfter: 10
    
  # SEMILLA PARA CONSTRUIR CLAVES MD5
  semillaMD5: verano
  
  # SERVICIO PARA CONTROL DE VISITAS  
  visitas:
    activo: false
    ws: http://api.ip-adress.com/?u=1062c309c5c054edc08fe578ef8f0dd94720c0&h=
    frecuenciaHorasBorrado: 5
  
  # FIRMAS DE LA WEB
  signatures:
    links: 'www.albatronic.com'
    services:
      'es': 'Diseño web,Venta Online,Posicionamiento web'
      'en': 'Web design,eCommerce,SEO'
      'fr': ''
    locations: 'Granada,Madrid,Malaga'

  # LONGITUD MÁXIMA PARA LAS URLS Y NOMBRES AMIGABLES
  maxLengthUrlsFriendly: 50
  # NUMERO MAXIMO DE PAGINAS
  numMaxPages: 100
  # NUMERO MAXIMO DE DOCUMENTOS
  numMaxDocuments: 0
  # NUMERO MAXIMO DE IMAGENES EN LA GALERIA
  numMaxGalery: 0
  # NUMERO MAXIMO DE VIDEOS
  numMaxVideos: 0
  # NUMERO MAXIMO DE AUDIOS
  numMaxAudios: 0
  # TIPOS DE ARCHIVOS PERMITIDOS PARA UPLOAD
  allowTypes: 'jpg,png,gif,pdf,docx,mp3,avi,pps'
  # MODULOS QUE TIENEN GESTION DE ETIQUETAS (lista separada por comas)
  modulosConEtiquetas: 'GconContenidos'
  # BLOQUEAR ROBOTS DE BUSQUEDA
  blockRobots: false
  
  # MOTOR DE ENVIO DE CORREOS
  mailer:
    plugin_dir: bin/PHPMailer_5.2.1/
    plugin_file: class.phpmailer.php
    motor: PHPMailer
    socket: smtp
    port: 25
    host: smtp.articoestudio.com
    smtp_auth: true
    user_name: info@articoestudio.com
    password: Goanita2012
    from: info@articoestudio.com
    from_name: Web Master
    timeout: 30
    mensajeExito: 'Su mensaje ha sido enviado correctamente.'
    mensajeError: 'Por problemas técnicos, el mensaje no ha podido ser procesado en estos momentos.'
    textoLOPD: '<p>Este correo electrónico y cualquier fichero adjunto a él son confidenciales y han sido creado exclusivamente para el uso de la persona a la que están dirigidos. Por ello, se informa a quien lo reciba por error que la información contenida en el mismo es reservada y su uso no autorizado está prohibido legalmente, por lo que en tal caso le rogamos nos lo comunique y proceda a borrarlo de inmediato.</p><p>La publicación, uso, diseminación, reenvío, impresión o copia no autorizados de este correo electrónico o cualquiera de los ficheros adjuntos al mismo, están estrictamente prohibidos.</p>'

  # MOTOR PARA DOCUMENTOS EXCEL
  excel: bin/PHPExcel/PHPExcel.php

  # MOTOR PARA GENERAR DOCUMENTOS PDF
  pdf: bin/pdf/fpdf.class.php

  # MOTOR PARA GRAFICOS DE BARRAS
  graph:
    -
      bin/jpgraph/src/jpgraph.php
    -
      bin/jpgraph/src/jpgraph_line.php
    -
      bin/jpgraph/src/jpgraph_bar.php

  # MOTOR DE TEMPLATES
  twig:
    motor: bin/Twig-1.11.1/lib/Twig/Autoloader.php
    templates_folder: modules
    debug_mode: false
    cache_folder: tmp
    charset: null

  # PROYECTOS Y CONEXIONES A LAS BASES DE DATOS
  # LA CARPETA DE CADA PROYECTO SE INDICA EL NODO FOLDER Y SE ENTIENDE
  # RESPECTO AL DOCUMENT_ROOT Y NO AL Cpanel
  #
  # EN PRODUCCION EL FOLDER SERÁ "/"
  conections:
    pcae:
      title: Albatronic Cloud Solutions
      description:
      folder: /Pcae
      dbEngine: mysql
      host: qpz135.dbname.net
      user: qpz135
      password: Rtve2013
      database: qpz135 
